const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  SALESPERSON: 'SALESPERSON',
};

const ORDER_STATUS = {
  CREATED: 'CREATED',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  CANCELED: 'CANCELED',
};

const SUB_STATUS = {
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  CANCELED: 'CANCELED',
};

const PLAN_CYCLE = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
};

const ORDER_LINE_KIND = {
  PLAN: 'PLAN',
  ADDON: 'ADDON',
};

const COMMISSION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  PAID: 'PAID',
};

module.exports = {
  ROLES,
  ORDER_STATUS,
  SUB_STATUS,
  PLAN_CYCLE,
  ORDER_LINE_KIND,
  COMMISSION_STATUS,
};
