export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  SALESPERSON: 'SALESPERSON',
};

export const ORDER_STATUS = {
  CREATED: 'CREATED',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
  CANCELED: 'CANCELED',
};

export const SUB_STATUS = {
  ACTIVE: 'ACTIVE',
  PAST_DUE: 'PAST_DUE',
  CANCELED: 'CANCELED',
};

export const PLAN_CYCLE = {
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
};

export const ORDER_LINE_KIND = {
  PLAN: 'PLAN',
  ADDON: 'ADDON',
};
